import BaseContainer from "@/components/containers/Container";
import "./globals.css";
import { Inter, Roboto, Montserrat } from "next/font/google";
import { Providers } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: "300",
});
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Mercado Libre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <main>
            <BaseContainer>{children}</BaseContainer>
          </main>
        </Providers>
      </body>
    </html>
  );
}
